### ISSUE TITLE
pmd command not found.

### ISSUE THREAD

**Issue by eefi0077** [sfdx-actions/pmd#1]
Hey trying to use this Github Action but I am running to one issue. I am using sfdx-actions/pmd@v9, but when I was using sfdx-actions/pmd@v1 it was giving me output under the 
uses: sfdx-actions@v1 when I switched to v9 I am getting pmd command not found. When I use v1 it errors out on the _uses_ section.

**actions file**

```    runs-on: ubuntu-latest

    steps:
      - uses: sfdx-actions/pmd@v9
      - name: run-pmd
        run: pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text
```

**Output**

Set up job              2s
  Run actions/checkout@v1           1s
  Run sfdx-actions/pmd@v9           2s
Run sfdx-actions/pmd@v9
Run sfdx-actions/pmd@v9
  run-pmd0s
##[error]Process completed with exit code 127.
Run pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text
/home/runner/work/_temp/483de406-35ea-4920-831d-0b2aefec05e7.sh: line 1: pmd: command not found
##[error]Process completed with exit code 127.
  Complete job

**Comment by mahavrilla** [comment]
I think this issue is that since it's JS the `executePMD()` is running before `installPMD()` is finished. These should be a promise, or just call `executePMD()` within `installPMD()`

https://github.com/sfdx-actions/pmd/blob/master/index.js#L4-L9

**Comment by fechanique** [comment]
The problem is that I'm trying to create an alias so you can use "pmd" to execute actions, but I can't for the moment solve it, so maybe for the moment the best solution is calling the executable direclty

**Comment by mahavrilla** [comment]
Oh that makes sense. I'm not 100% confident in that process, but I'd wonder if it's possible to release a version without using aliases as you said. I'd be willing to help get it working with alias.

I see a great opportunity for this action (thank you for creating it) so wondering the level of effort to release a version calling it directly?

**Comment by fechanique** [comment]
Ok, for the moment is going to work with something like: $HOME/pmd/bin/run.sh pmd

If you have any suggestion creating an alias, are welcome!!
